export const genreSeeds = [{ "id": 1, "name": "Documentary", "isDeleted": true },
{ "id": 2, "name": "Drama", "isDeleted": false },
{ "id": 3, "name": "Comedy|Sci-Fi", "isDeleted": false },
{ "id": 4, "name": "Drama|Thriller", "isDeleted": false },
{ "id": 5, "name": "Adventure|Animation|Children|Comedy|Crime|Fantasy|Mystery", "isDeleted": false },
{ "id": 6, "name": "Western", "isDeleted": false },
{ "id": 7, "name": "Drama|Romance", "isDeleted": true },
{ "id": 8, "name": "Documentary", "isDeleted": true },
{ "id": 9, "name": "Action|Sci-Fi|Thriller", "isDeleted": false },
{ "id": 10, "name": "Drama|Thriller", "isDeleted": true }]