export const movieSeeds = [
  {
    id: 1,
    name: 'Barbarian Queen II: The Empress Strikes Back',
    duration: 1,
    disabled: true,
    price: 762,
  },
  {
    id: 2,
    name: 'Rise of the Footsoldier',
    duration: 2,
    disabled: false,
    price: 762,
  },
  {
    id: 3,
    name: 'I Heart Monster Movies',
    duration: 2,
    disabled: false,
    price: 762,
  },
  { id: 4, name: 'Bride Wars', duration: 1, disabled: false, price: 762 },
  {
    id: 5,
    name: 'Blood on the Moon',
    duration: 2,
    disabled: false,
    price: 762,
  },
  { id: 6, name: 'Cookout, The', duration: 2, disabled: false, price: 762 },
  {
    id: 7,
    name: 'Killjoy Goes to Hell',
    duration: 1,
    disabled: false,
    price: 762,
  },
  {
    id: 8,
    name: 'American Pie Presents Beta House (American Pie 6: Beta House)',
    duration: 2,
    disabled: false,
    price: 762,
  },
  { id: 9, name: 'Great Lie, The', duration: 2, disabled: false, price: 762 },
  { id: 10, name: 'Oliver & Company', duration: 1, disabled: true, price: 762 },
];
